repos:
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
    args: [--line-length=79]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    args: [--ignore-missing-imports, --strict-optional]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-yaml
